# Auto-generated V2 content for Datos en orden portfolio.

PROFILE = {'name': 'Datos en orden',
 'title': 'Business Automation & Information Systems',
 'subtitle': 'Python • APIs • Data • AI • OCR • Automation • Information Systems',
 'email': 'datosenorden@gmail.com',
 'github': 'https://github.com/Aylin-guez',
 'linkedin': 'https://www.linkedin.com/in/aylin-rodr%C3%ADguez/',
 'upwork': 'https://www.upwork.com/freelancers/~0118df067f42a06dba?mp_source=share',
 'fiverr': 'https://www.fiverr.com/sellers/aylinrodriguezz/edit'}

ENGINE_PRODUCTS_ROOT = 'D:\\SecondLifeEngine\\products'

DEFAULT_GITHUB_URL = 'https://github.com/Aylin-guez/document-intelligence-demo'

FEATURED_SERVICES = [{'title': 'Business Automation',
  'text': 'Automate repetitive work, internal processes, reporting routines and operational workflows.'},
 {'title': 'Information Systems',
  'text': 'Design custom systems to centralize data, track processes and support decision-making.'},
 {'title': 'Data Engineering',
  'text': 'Build ETL workflows, SQL processes, data cleaning pipelines, dashboards and analytics outputs.'},
 {'title': 'AI & Document Intelligence',
  'text': 'Use OCR, LLMs, classification and extraction to transform documents into structured information.'},
 {'title': 'Software Integration',
  'text': 'Connect spreadsheets, APIs, databases and business platforms into maintainable workflows.'},
 {'title': 'Technical Consulting',
  'text': 'Map business problems, document architecture and define practical automation roadmaps.'}]

WHAT_I_BUILD = [{'icon': '⚙️',
  'title': 'Internal Tools',
  'text': 'Small applications and workflows that replace manual operational tasks.'},
 {'icon': '📊',
  'title': 'Dashboards & KPIs',
  'text': 'Reporting systems for management, operations and recurring indicators.'},
 {'icon': '🗃️',
  'title': 'Data Pipelines',
  'text': 'Processes that clean, transform, validate and move data across sources.'},
 {'icon': '📄',
  'title': 'Document Intelligence',
  'text': 'OCR, PDF extraction, classification, traceability and automatic documents.'},
 {'icon': '🤖',
  'title': 'AI Workflows',
  'text': 'LLM-assisted analysis, classification, drafting, search and operational assistants.'},
 {'icon': '🌐',
  'title': 'APIs & Integrations',
  'text': 'Connections between spreadsheets, web apps, databases and external services.'},
 {'icon': '🏛️',
  'title': 'Public Information Systems',
  'text': 'Platforms that organize, validate and explain information from public sources.'},
 {'icon': '🔎',
  'title': 'Traceability Systems',
  'text': 'Evidence, claims, relationships, validation notes and audit-ready workflows.'}]

PROBLEMS = ['Manual Excel workflows that consume hours every week',
 'Disconnected systems, spreadsheets and data sources',
 'Repeated reports rebuilt manually every month',
 'Slow document review, PDF extraction or OCR work',
 'Messy operational data that needs cleaning and validation',
 'Compliance, audit or evidence traceability documentation',
 'Teams that need dashboards, KPIs or executive reporting',
 'Processes that could become internal tools or automated workflows',
 'Public or institutional information that needs structure and transparency',
 'AI-assisted workflows for classification, analysis and drafting']

PROBLEMS_ES = ['Trabajo manual en Excel que consume horas cada semana',
 'Sistemas, planillas y fuentes de datos desconectadas',
 'Reportes repetitivos reconstruidos manualmente cada mes',
 'Revisión lenta de documentos, extracción desde PDF u OCR',
 'Datos operacionales desordenados que requieren limpieza y validación',
 'Documentación de compliance, auditoría o trazabilidad de evidencia',
 'Equipos que necesitan dashboards, KPIs o reportes ejecutivos',
 'Procesos que pueden convertirse en herramientas internas o automatizaciones',
 'Información pública o institucional que necesita estructura y transparencia',
 'Flujos asistidos por IA para clasificar, analizar y redactar']

SOLUTIONS = [{'title': 'Internal Operations Dashboard',
  'problem': 'Teams track operations across scattered spreadsheets and manual reports.',
  'solution': 'A centralized dashboard and data workflow that consolidates sources, validates data and exposes KPIs.',
  'tech': 'Python • SQL • Power BI • Excel • Automation'},
 {'title': 'Intelligent Document Processing',
  'problem': 'Documents and PDFs contain useful information, but reviewing them manually is slow and error-prone.',
  'solution': 'OCR and extraction workflows that convert PDFs and images into structured data, reports and searchable '
              'outputs.',
  'tech': 'Python • OCR • PDF Processing • Data Cleaning'},
 {'title': 'Traceability & Evidence Workflow',
  'problem': 'Claims, reports and evidence are difficult to connect and validate across many documents.',
  'solution': 'A traceability workflow that links sources, findings, validation notes and supporting evidence.',
  'tech': 'Python • Data Modeling • Reports • Audit Workflow'},
 {'title': 'Public Information Platform',
  'problem': 'Public information is usually dispersed across portals, PDFs and datasets.',
  'solution': 'A civic information system that ingests, organizes, validates and explains public data sources.',
  'tech': 'Python • PostgreSQL • ETL • Public Data • Transparency'},
 {'title': 'AI-Assisted Business Workflow',
  'problem': 'Teams repeat analysis, classification, drafting or review tasks that could be partially assisted by AI.',
  'solution': 'A workflow that combines business rules, LLMs, prompts and human review to speed up recurring work.',
  'tech': 'Python • LLMs • APIs • Automation • Human-in-the-loop'}]

SOLUTIONS_ES = [{'title': 'Dashboard Operacional Interno',
  'problem': 'Los equipos gestionan operaciones con planillas dispersas y reportes manuales.',
  'solution': 'Un dashboard y flujo de datos centralizado que consolida fuentes, valida información y muestra '
              'indicadores.',
  'tech': 'Python • SQL • Power BI • Excel • Automatización'},
 {'title': 'Procesamiento Inteligente de Documentos',
  'problem': 'Los documentos y PDFs contienen información útil, pero revisarlos manualmente es lento y propenso a '
             'errores.',
  'solution': 'Flujos OCR y extracción que convierten PDFs e imágenes en datos estructurados, reportes y salidas '
              'consultables.',
  'tech': 'Python • OCR • PDF Processing • Limpieza de Datos'},
 {'title': 'Flujo de Trazabilidad y Evidencia',
  'problem': 'Las afirmaciones, reportes y evidencias son difíciles de conectar y validar entre muchos documentos.',
  'solution': 'Un flujo de trazabilidad que relaciona fuentes, hallazgos, notas de validación y evidencia de respaldo.',
  'tech': 'Python • Modelamiento de Datos • Reportes • Auditoría'},
 {'title': 'Plataforma de Información Pública',
  'problem': 'La información pública suele estar dispersa entre portales, PDFs y datasets.',
  'solution': 'Un sistema cívico que ingiere, organiza, valida y explica fuentes de datos públicas.',
  'tech': 'Python • PostgreSQL • ETL • Datos Públicos • Transparencia'},
 {'title': 'Flujo de Negocio Asistido por IA',
  'problem': 'Los equipos repiten tareas de análisis, clasificación, redacción o revisión que podrían ser asistidas '
             'por IA.',
  'solution': 'Un flujo que combina reglas de negocio, LLMs, prompts y revisión humana para acelerar trabajo '
              'recurrente.',
  'tech': 'Python • LLMs • APIs • Automatización • Human-in-the-loop'}]

INDUSTRIES = ['Government & Public Data',
 'Finance & Compliance',
 'Construction',
 'Healthcare & Clinics',
 'Education',
 'Hospitality & Events',
 'Retail & Operations',
 'Professional Services',
 'Software Companies',
 'Small and Medium Businesses']

INDUSTRIES_ES = ['Gobierno y datos públicos',
 'Finanzas y compliance',
 'Construcción',
 'Salud y clínicas',
 'Educación',
 'Hotelería y eventos',
 'Retail y operaciones',
 'Servicios profesionales',
 'Empresas de software',
 'Pymes']

TECH_STACK = ['Python',
 'SQL',
 'PostgreSQL',
 'FastAPI',
 'APIs REST',
 'Power BI',
 'Excel Automation',
 'OCR',
 'PDF Processing',
 'LLMs / GenAI',
 'Data Pipelines',
 'ETL',
 'Git',
 'HTML/CSS/JavaScript',
 'Automation Scripts',
 'Information Architecture']

PORTFOLIO_CATEGORIES = ['Reports & Analytics',
 'Document Intelligence',
 'Business Operations',
 'Marketing & Sales',
 'Hospitality & Events',
 'Education / Course Products']

CASE_STUDIES = [{'slug': 'business_report',
  'title': 'Business Report',
  'category': 'Reports & Analytics',
  'description': 'Executive summaries, KPI tables, timelines and conclusions from structured business data.'},
 {'slug': 'audit_report',
  'title': 'Audit Report',
  'category': 'Reports & Analytics',
  'description': 'Findings, risks, evidence, recommendations and audit conclusions in one formal report.'},
 {'slug': 'traceability_matrix',
  'title': 'Traceability Matrix',
  'category': 'Reports & Analytics',
  'description': 'Evidence relationships, claims, validation notes and audit-ready traceability tables.'},
 {'slug': 'seo_audit_report',
  'title': 'SEO Audit Report',
  'category': 'Reports & Analytics',
  'description': 'Website health, SEO priorities, technical findings and a practical action plan.'},
 {'slug': 'competitor_analysis_report',
  'title': 'Competitor Analysis Report',
  'category': 'Reports & Analytics',
  'description': 'Market positioning, competitor matrix, opportunity map and next-step strategy.'},
 {'slug': 'customer_feedback_report',
  'title': 'Customer Feedback Report',
  'category': 'Reports & Analytics',
  'description': 'Survey and review themes converted into risks, insights and operational actions.'},
 {'slug': 'nonprofit_impact_report',
  'title': 'Nonprofit Impact Report',
  'category': 'Reports & Analytics',
  'description': 'Program metrics, funding use and donor-ready impact storytelling.'},
 {'slug': 'construction_project_status_report',
  'title': 'Construction Project Status Report',
  'category': 'Reports & Analytics',
  'description': 'Weekly project progress, milestone tracking, budget watch and risk notes.'},
 {'slug': 'investigation_dossier',
  'title': 'Investigation Dossier',
  'category': 'Document Intelligence',
  'description': 'Structured dossier with indexes, timelines, people, evidence and findings.'},
 {'slug': 'technical_documentation',
  'title': 'Technical Documentation',
  'category': 'Document Intelligence',
  'description': 'System guides, workflows, architecture notes, setup instructions and technical notes.'},
 {'slug': 'legal_document_bundle',
  'title': 'Legal Document Bundle',
  'category': 'Document Intelligence',
  'description': 'Parties, document index, clauses, obligations and review notes for automation demos.'},
 {'slug': 'meeting_minutes_generator',
  'title': 'Meeting Minutes Generator',
  'category': 'Document Intelligence',
  'description': 'Attendees, agenda, decisions, action items, risks and follow-up in a clean PDF.'},
 {'slug': 'proposal_generator',
  'title': 'Proposal Generator',
  'category': 'Business Operations',
  'description': 'Commercial proposals with scope, deliverables, pricing, timeline and terms.'},
 {'slug': 'property_dossier',
  'title': 'Property Dossier',
  'category': 'Business Operations',
  'description': 'Real estate dossier with summary, features, pricing, location and next steps.'},
 {'slug': 'corporate_manual',
  'title': 'Corporate Manual',
  'category': 'Business Operations',
  'description': 'Internal manual with roles, policies, procedures, onboarding and compliance sections.'},
 {'slug': 'product_catalog',
  'title': 'Product Catalog',
  'category': 'Business Operations',
  'description': 'Product lists, prices, categories, availability, featured items and ordering notes.'},
 {'slug': 'invoice_quote_generator',
  'title': 'Invoice & Quote Generator',
  'category': 'Business Operations',
  'description': 'Quotes, proformas, line items, taxes, payment terms and approval sections.'},
 {'slug': 'hr_employee_reports',
  'title': 'HR Employee Reports',
  'category': 'Business Operations',
  'description': 'Employee profile, onboarding, training, evaluation, attendance and development plan.'},
 {'slug': 'brand_book',
  'title': 'Brand Book',
  'category': 'Marketing & Sales',
  'description': 'Brand values, colors, typography, voice, tone and usage guidelines.'},
 {'slug': 'social_media_content_calendar',
  'title': 'Social Media Content Calendar',
  'category': 'Marketing & Sales',
  'description': 'Campaign summary, content pillars, channel mix, weekly calendar and production tasks.'},
 {'slug': 'etsy_shop_optimization_report',
  'title': 'Etsy Shop Optimization Report',
  'category': 'Marketing & Sales',
  'description': 'Marketplace listing audit with keyword, photo, conversion and 30-day improvement notes.'},
 {'slug': 'email_marketing_campaign_report',
  'title': 'Email Marketing Campaign Report',
  'category': 'Marketing & Sales',
  'description': 'Email metrics, creative notes, segmentation ideas and next-test planning.'},
 {'slug': 'sales_pipeline_report',
  'title': 'Sales Pipeline Report',
  'category': 'Marketing & Sales',
  'description': 'Pipeline stages, forecast value, deal risks and next actions for sales teams.'},
 {'slug': 'creator_media_kit',
  'title': 'Creator Media Kit',
  'category': 'Marketing & Sales',
  'description': 'Creator profile, audience metrics, partnership packages and brand collaboration notes.'},
 {'slug': 'restaurant_menu_profit_report',
  'title': 'Restaurant Menu Profit Report',
  'category': 'Hospitality & Events',
  'description': 'Menu profitability, item roles, pricing notes and operator action plan.'},
 {'slug': 'airbnb_guest_welcome_book',
  'title': 'Airbnb Guest Welcome Book',
  'category': 'Hospitality & Events',
  'description': 'Guest arrival guide, house rules, local recommendations and checkout details.'},
 {'slug': 'event_planning_pack',
  'title': 'Event Planning Pack',
  'category': 'Hospitality & Events',
  'description': 'Event snapshot, vendor tracker, budget, run-of-show and coordinator checklist.'},
 {'slug': 'grant_funding_proposal',
  'title': 'Grant Funding Proposal',
  'category': 'Education / Course Products',
  'description': 'Project summary, organization profile, activities, budget, impact and sustainability.'},
 {'slug': 'course_launch_planner',
  'title': 'Course Launch Planner',
  'category': 'Education / Course Products',
  'description': 'Course offer, launch timeline, asset checklist, metrics and weekly execution plan.'}]

HOME_FEATURED_SLUGS = ['business_report',
 'audit_report',
 'traceability_matrix',
 'technical_documentation',
 'investigation_dossier',
 'legal_document_bundle']

PROJECTS = [{'title': 'DatosEnOrden Public Information Platform',
  'text': 'Public demonstration of a traceable information system for organizing, validating and connecting public '
          'data sources.',
  'tags': 'Python - PostgreSQL - Public Data - Traceability',
  'link': 'https://github.com/Aylin-guez/DatosEnOrden'},
 {'title': 'OCR Document Intelligence Pipeline',
  'text': 'Extracts data from PDFs and images and turns it into structured outputs.',
  'tags': 'Python - OCR - Reporting',
  'link': 'https://github.com/Aylin-guez/document-intelligence-demo'},
 {'title': 'Messy Data Reconstruction Pipeline',
  'text': 'Normalizes messy operational data into structured tables and usable outputs.',
  'tags': 'Python - Data Cleaning - ETL',
  'link': 'https://github.com/Aylin-guez/messy-data-reconstruction-pipeline'},
 {'title': 'PDF Intelligence Pipeline',
  'text': 'Processes PDFs with extraction, classification and automated document logic.',
  'tags': 'Python - PDF Automation - OCR',
  'link': 'https://github.com/Aylin-guez/pdf_intelligence_pipeline'},
 {'title': 'Entity Relationship Dashboard',
  'text': 'Visualizes entity connections, patterns and operational relationships.',
  'tags': 'Data - Dashboard - Analysis',
  'link': 'https://github.com/Aylin-guez/entity_relationship_dashboard'},
 {'title': 'Report Cross Reference Automation',
  'text': 'Cross-references report sections, sources and supporting evidence automatically.',
  'tags': 'Python - Reporting - Automation',
  'link': 'https://github.com/Aylin-guez/report-cross-reference-automation'},
 {'title': 'Financial Transactions Dashboard',
  'text': 'Turns transaction records into interactive financial tracking views.',
  'tags': 'Data - Finance - Dashboard',
  'link': 'https://github.com/Aylin-guez/financial-transactions-dashboard'}]

TEXT = {'en': {'lang': 'en',
        'other_lang_url': 'es.html',
        'other_lang_label': 'ES',
        'nav_services': 'Services',
        'nav_portfolio': 'Document Catalog',
        'nav_projects': 'My Public Projects',
        'nav_contact': 'Contact',
        'hero_text': 'I design and build business systems that automate operations, connect data across multiple '
                     'platforms and help organizations make better decisions. From internal tools and dashboards to '
                     'AI-powered workflows, document intelligence and public information systems.',
        'hero_panel_title': 'Business Automation & Information Systems',
        'hero_panel_count': '6+',
        'hero_panel_label': 'automation areas',
        'hero_panel_stack': 'Python • APIs • Data • AI • OCR • Systems',
        'services_label': 'Services',
        'services_title': 'Core services',
        'services_intro': 'I help teams turn manual, repetitive or messy information processes into reliable systems, '
                          'workflows and decision-support tools.',
        'build_label': 'Capabilities',
        'build_title': 'What I build',
        'build_intro': 'The same technical base can support clients, software partners or internal teams that need '
                       'practical automation.',
        'problems_label': 'Problems',
        'problems_title': 'Problems I solve',
        'problems_intro': 'I focus on concrete operational pain: repeated work, scattered information, slow reporting '
                          'and processes that depend too much on manual effort.',
        'solutions_label': 'Example Solutions',
        'solutions_title': 'Example solutions',
        'solutions_intro': 'These are examples of the type of systems and workflows I can design or implement. Some '
                           'code is public; commercial or strategic systems can remain private.',
        'industries_label': 'Industries',
        'industries_title': 'Industries where this applies',
        'industries_intro': 'The workflows can adapt to different industries because the underlying problems are '
                            'usually the same: data, documents, processes and decisions.',
        'tech_label': 'Tech Stack',
        'tech_title': 'Technologies and tools',
        'portfolio_label': 'Document Intelligence',
        'portfolio_title': 'Document automation catalog',
        'portfolio_intro': 'This catalog shows automated document and report workflows. It remains as a specialized '
                           'area inside a broader automation and information systems portfolio.',
        'featured_title': 'Document workflows showcase',
        'featured_intro': 'Selected workflows focused on corporate reporting, compliance and structured documentation.',
        'projects_label': 'My Public Projects',
        'projects_title': 'My public code examples',
        'projects_intro': 'A selection of my public repositories and demos. Some business ideas, client work and '
                          'strategic tools are intentionally private.',
        'view_showcase': 'View Showcase',
        'github': 'GitHub',
        'view_project': 'View project',
        'automate_label': 'Approach',
        'automate_title': 'From messy process to usable system',
        'checklist': ['Understand the real workflow before automating it',
                      'Identify repetitive steps, data sources and decision points',
                      'Build practical tools that reduce manual work and errors',
                      'Document the process so it can be maintained and improved',
                      'Keep sensitive or strategic systems private when needed'],
        'contact_title': 'Need to automate a process, report or information workflow?',
        'contact_text': 'Send me a message and I can review the process with you.',
        'footer': 'Business Automation • Information Systems • AI Solutions'},
 'es': {'lang': 'es',
        'other_lang_url': 'index.html',
        'other_lang_label': 'EN',
        'nav_services': 'Servicios',
        'nav_portfolio': 'Catálogo Documental',
        'nav_projects': 'Mis Proyectos Públicos',
        'nav_contact': 'Contacto',
        'hero_text': 'Diseño y construyo sistemas de negocio que automatizan operaciones, conectan datos entre '
                     'distintas plataformas y ayudan a las organizaciones a tomar mejores decisiones. Desde '
                     'herramientas internas y dashboards hasta flujos con IA, inteligencia documental y sistemas de '
                     'información pública.',
        'hero_panel_title': 'Automatización de Negocio y Sistemas de Información',
        'hero_panel_count': '6+',
        'hero_panel_label': 'áreas de automatización',
        'hero_panel_stack': 'Python • APIs • Datos • IA • OCR • Sistemas',
        'services_label': 'Servicios',
        'services_title': 'Servicios principales',
        'services_intro': 'Ayudo a convertir procesos manuales, repetitivos o con información desordenada en sistemas '
                          'confiables, flujos automatizados y herramientas para tomar decisiones.',
        'build_label': 'Capacidades',
        'build_title': 'Qué construyo',
        'build_intro': 'La misma base técnica puede servir a clientes, empresas de software o equipos internos que '
                       'necesitan automatización práctica.',
        'problems_label': 'Problemas',
        'problems_title': 'Problemas que resuelvo',
        'problems_intro': 'Me enfoco en dolores operativos concretos: trabajo repetitivo, información dispersa, '
                          'reportes lentos y procesos que dependen demasiado del esfuerzo manual.',
        'solutions_label': 'Soluciones ejemplo',
        'solutions_title': 'Ejemplos de soluciones',
        'solutions_intro': 'Estos son ejemplos del tipo de sistemas y flujos que puedo diseñar o implementar. Parte '
                           'del código puede ser público; sistemas comerciales o estratégicos pueden mantenerse '
                           'privados.',
        'industries_label': 'Industrias',
        'industries_title': 'Industrias donde aplica',
        'industries_intro': 'Los flujos se adaptan a distintas industrias porque los problemas de fondo suelen '
                            'repetirse: datos, documentos, procesos y decisiones.',
        'tech_label': 'Tecnologías',
        'tech_title': 'Tecnologías y herramientas',
        'portfolio_label': 'Inteligencia Documental',
        'portfolio_title': 'Catálogo de automatización documental',
        'portfolio_intro': 'Este catálogo muestra flujos automatizados de documentos y reportes. Queda como un área '
                           'especializada dentro de un portafolio más amplio de automatización y sistemas de '
                           'información.',
        'featured_title': 'Muestra de flujos documentales',
        'featured_intro': 'Flujos seleccionados enfocados en reportes corporativos, compliance y documentación '
                          'estructurada.',
        'projects_label': 'Mis Proyectos Públicos',
        'projects_title': 'Mis ejemplos públicos de código',
        'projects_intro': 'Una selección de mis repositorios públicos y demos. Algunas ideas de negocio, trabajos para '
                          'clientes y herramientas estratégicas se mantienen privadas intencionalmente.',
        'view_showcase': 'Ver showcase',
        'github': 'GitHub',
        'view_project': 'Ver proyecto',
        'automate_label': 'Enfoque',
        'automate_title': 'De proceso desordenado a sistema usable',
        'checklist': ['Entender el flujo real antes de automatizarlo',
                      'Identificar pasos repetitivos, fuentes de datos y puntos de decisión',
                      'Construir herramientas prácticas que reduzcan trabajo manual y errores',
                      'Documentar el proceso para mantenerlo y mejorarlo',
                      'Mantener privados los sistemas sensibles o estratégicos cuando sea necesario'],
        'contact_title': '¿Necesitas automatizar un proceso, reporte o flujo de información?',
        'contact_text': 'Envíame un mensaje y puedo revisar el proceso contigo.',
        'footer': 'Automatización de Negocio • Sistemas de Información • Soluciones con IA'}}

